### ISSUE TITLE
`npm run install-jekyll` fails for Ruby 3

### ISSUE THREAD

**Issue by ycsh-w** [CloudCannon/vonge-jekyll-bookshop-template#4]
Thanks for the great template! It looks really nice. I encountered the following problem while trying to run the code locally.

```
➜  vonge-jekyll-bookshop-template git:(main) ✗ npm run install-jekyll

> install-jekyll
> BUNDLE_GEMFILE=site/Gemfile bundle install

Fetching gem metadata from https://rubygems.org/.........
Using bundler 2.2.32
Using citrus 3.0.2
Using dry-inflector 0.2.1
Using node-runner-temp-fix-windows 1.0.1
Using eventmachine 1.2.7
Using toml-rb 2.1.0
Using concurrent-ruby 1.1.9
Using ffi 1.15.4
Using rb-fsevent 0.11.0
Using rexml 3.2.5
Using liquid 4.0.3
Using mercenary 0.4.0
Using forwardable-extended 2.6.0
Using rouge 3.26.1
Using safe_yaml 1.0.5
Using pathutil 0.16.2
Using public_suffix 4.0.6
Using colorator 1.1.0
Using nuggets 1.6.0
Using addressable 2.8.0
Using i18n 1.8.10
Using jekyll-tagging 1.1.0
Using rb-inotify 0.10.1
Using kramdown 2.3.1
Using unicode-display_width 1.8.0
Using listen 3.7.0
Using sassc 2.4.0
Using kramdown-parser-gfm 1.1.0
Using jekyll-sass-converter 2.1.0
Using http_parser.rb 0.6.0
Using terminal-table 2.0.0
Using em-websocket 0.5.2
Using jekyll-watch 2.2.1 from https://github.com/CloudCannon/jekyll-watch (at master@3289405)
Using jekyll 4.2.1
Using cloudcannon-jekyll-bookshop 2.2.2
Fetching jekyll-pagebreak 0.6.0
Using jekyll-sitemap 1.4.0
Using jekyll-bookshop 2.2.2
Installing jekyll-pagebreak 0.6.0 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory:
/usr/local/lib/ruby/gems/3.0.0/gems/jekyll-pagebreak-0.6.0/ext
/usr/local/opt/ruby/bin/ruby -I /usr/local/Cellar/ruby/3.0.3/lib/ruby/3.0.0 -r
./siteconf20211229-69194-xua6zj.rb extconf.rb
extconf.rb:37:in `initialize': No such file or directory @ rb_sysopen -
https://github.com/CloudCannon/pagebreak/releases/download/v0.6.0/pagebreak-v0.6.0-x86_64-apple-darwin.tar.gz
(Errno::ENOENT)
	from extconf.rb:37:in `open'
	from extconf.rb:37:in `<main>'
Installing Pagebreak

extconf failed, exit code 1

Gem files will remain installed in
/usr/local/lib/ruby/gems/3.0.0/gems/jekyll-pagebreak-0.6.0 for inspection.
Results logged to
/usr/local/lib/ruby/gems/3.0.0/extensions/x86_64-darwin-21/3.0.0/jekyll-pagebreak-0.6.0/gem_make.out

/usr/local/Cellar/ruby/3.0.3/lib/ruby/3.0.0/rubygems/ext/builder.rb:93:in
`run'
/usr/local/Cellar/ruby/3.0.3/lib/ruby/3.0.0/rubygems/ext/ext_conf_builder.rb:47:in
`block in build'
  /usr/local/Cellar/ruby/3.0.3/lib/ruby/3.0.0/tempfile.rb:317:in `open'
/usr/local/Cellar/ruby/3.0.3/lib/ruby/3.0.0/rubygems/ext/ext_conf_builder.rb:26:in
`build'
/usr/local/Cellar/ruby/3.0.3/lib/ruby/3.0.0/rubygems/ext/builder.rb:159:in
`build_extension'
/usr/local/Cellar/ruby/3.0.3/lib/ruby/3.0.0/rubygems/ext/builder.rb:193:in
`block in build_extensions'
/usr/local/Cellar/ruby/3.0.3/lib/ruby/3.0.0/rubygems/ext/builder.rb:190:in
`each'
/usr/local/Cellar/ruby/3.0.3/lib/ruby/3.0.0/rubygems/ext/builder.rb:190:in
`build_extensions'
/usr/local/Cellar/ruby/3.0.3/lib/ruby/3.0.0/rubygems/installer.rb:845:in
`build_extensions'
/usr/local/Cellar/ruby/3.0.3/lib/ruby/3.0.0/bundler/rubygems_gem_installer.rb:71:in
`build_extensions'
/usr/local/Cellar/ruby/3.0.3/lib/ruby/3.0.0/bundler/rubygems_gem_installer.rb:28:in
`install'
/usr/local/Cellar/ruby/3.0.3/lib/ruby/3.0.0/bundler/source/rubygems.rb:200:in
`install'
/usr/local/Cellar/ruby/3.0.3/lib/ruby/3.0.0/bundler/installer/gem_installer.rb:54:in
`install'
/usr/local/Cellar/ruby/3.0.3/lib/ruby/3.0.0/bundler/installer/gem_installer.rb:16:in
`install_from_spec'
/usr/local/Cellar/ruby/3.0.3/lib/ruby/3.0.0/bundler/installer/parallel_installer.rb:186:in
`do_install'
/usr/local/Cellar/ruby/3.0.3/lib/ruby/3.0.0/bundler/installer/parallel_installer.rb:177:in
`block in worker_pool'
/usr/local/Cellar/ruby/3.0.3/lib/ruby/3.0.0/bundler/worker.rb:62:in
`apply_func'
/usr/local/Cellar/ruby/3.0.3/lib/ruby/3.0.0/bundler/worker.rb:57:in `block in
process_queue'
  /usr/local/Cellar/ruby/3.0.3/lib/ruby/3.0.0/bundler/worker.rb:54:in `loop'
/usr/local/Cellar/ruby/3.0.3/lib/ruby/3.0.0/bundler/worker.rb:54:in
`process_queue'
/usr/local/Cellar/ruby/3.0.3/lib/ruby/3.0.0/bundler/worker.rb:91:in `block (2
levels) in create_threads'

An error occurred while installing jekyll-pagebreak (0.6.0), and
Bundler cannot continue.

In Gemfile:
  jekyll-pagebreak
```

After reading [this](https://stackoverflow.com/questions/65937714/no-such-file-or-directory-rb-sysopen-for-external-url-rails-6-11-ruby-3) I realized it's a Ruby version problem. And after installing specifically Ruby 2.7 I get it working locally.

I am not a Ruby programmer so it takes me a long time to figure out what happens. It would be great if you can mention somewhere that there is this requirement for Ruby version.

 Thanks!

**Comment by bglw** [comment]
Thanks for this! It looks like it actually hitting the issue on a dependency we maintain, https://github.com/CloudCannon/pagebreak . 

I'll look at shipping support for Ruby 3.0 there, and then hopefully we don't need to have a version requirement.

**Comment by bglw** [comment]
Sorry for the delay @Yuchen-Wang-SH @chubby1523 — Pagebreak's `jekyll-pagebreak` v0.9.1 has gone out which now supports Ruby 3.0.
